blueprint:
  name: Shabbat Switcher
  description: >
    # 🕎 Shabbat Switcher

    **Version: .1**


    Automation that evaluates conditions and switches HA to Shabbat Mode

    Requires the Jewish Calendar integration

    <details>
    <summary>How it works:</summary>


      - **Trigger:**
        - Going to be lots of description here
    </details>


    Welcome to reach out for questions.


    Required = *
  domain: automation
  input:
    values:
      name: "Trigger *"
      icon: mdi:cog-outline
      collapsed: false
      input:
        shabbat_trigger:
          name: Sensor which activates Shabbat/Yom Tov
          description: >
            The sensor which activates this automation, generally from Jewish Calendar
          default: binary_sensor.jewish_calendar_issur_melacha_in_effect
          selector:
            entity:
              filter:
                domain:
                  - binary_sensor
              multiple: false
        shabbat_status:
          name: Shabbat Status
          description: >
            The internal variable used to denote Shabbat mode for the house
          default: input_boolean.shabbat_active
          selector:
            entity:
              filter:
                domain:
                  - input_boolean
              multiple: false
        shabbat_disable:
          name: Shabbat Mode Disable
          description: >
            These prevent the house from going into Shabbat mode
          default: input_boolean.away
          selector:
            entity:
              filter:
                domain:
                  - input_boolean
              multiple: true
        early_start_trigger:
          name: Early Start Time
          description: >
            This is the latest time the house will go into Shabbat mode even if not yet candle lighting
          default: "19:30:00"
          selector:
            time:
        erev_sensor:
          name: Sensor which identifies if it is erev shabbat
          description: >
            The sensor which activates this automation, generally from Jewish Calendar
          default: binary_sensor.jewish_calendar_erev_shabbat_hag
          selector:
            entity:
              filter:
                domain:
                  - binary_sensor
              multiple: false
            

mode: single

variables:
  shabbat_trigger: !input shabbat_trigger
  shabbat_disable: !input shabbat_disable

    
triggers:
  - entity_id:
      - !input shabbat_trigger
    to: null
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{trigger.to_state.state == 'on'}}"
          - condition: state
            entity_id: !input shabbat_disable
            state: "off"
            match: any
        sequence:
          - target:
              entity_id: input_boolean.shabbat_active
            data: {}
            action: input_boolean.turn_on
      - conditions:
          - condition: template
            value_template: "{{trigger.to_state.state == 'off'}}"
          - condition: state
            entity_id: input_boolean.shabbat_active
            state: "on"
        sequence:
          - target:
              entity_id: input_boolean.shabbat_active
            data: {}
            action: input_boolean.turn_off
    default: []

    
