blueprint:
  name: Shabbat Mode
  description: >
    # 🕎 Shabbat Mode

    **Version: .1**


    Shabbat Mode master automation

    Requires the Jewish Calendar integration

    <details>
    <summary>How it works:</summary>


      - **Trigger:**
        - Going to be lots of description here
    </details>


    Welcome to reach out for questions.


    Required = *
  domain: automation
  input:
    trigger:
      name: "Config *"
      icon: mdi:cog-outline
      collapsed: true
      input:
        shabbat_trigger:
          name: Trigger Sensor
          description: >
            The sensor which triggers this automation, generally from Jewish Calendar


          default: input_boolean.shabbat_active
          selector:
            entity:
              filter:
                domain:
                  - binary_sensor
              multiple: false
              
    start_settings:
      name: "Start *"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        start_scenes:
          name: Start Scenes, Scripts, Automations
          description: >
            

          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    end_settings:
      name: "End *"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    dinner_settings:
      name: "dinner"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_dinner_schedule:
          name: Enable dinner schedule
          description: >
            This setting enables the dinner schedule.
          default: dinner_schedule_disabled
          selector:
            select:
              options:
                - label: Enable dinner schedule
                  value: "dinner_schedule_enabled"
                - label: Disable dinner schedule
                  value: "dinner_schedule_disabled"                     
        dinner_time:
          name: dinner set time
          description: >

          default: "7:30:00"
          selector:
            time:       
        dinner_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script
                           
    evening_settings:
      name: "Evening"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_evening_schedule:
          name: Enable evening schedule
          description: >
            This setting enables the evening schedule.
          default: evening_schedule_disabled
          selector:
            select:
              options:
                - label: Enable evening schedule
                  value: "evening_schedule_enabled"
                - label: Disable evening schedule
                  value: "evening_schedule_disabled"                     
        evening_time:
          name: Evening set time
          description: >

          default: "22:00:00"
          selector:
            time:       
        evening_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    night_settings:
      name: "Night"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_night_schedule:
          name: Enable night schedule
          description: >
            This setting enables the night schedule.
          default: night_schedule_disabled
          selector:
            select:
              options:
                - label: Enable night schedule
                  value: "night_schedule_enabled"
                - label: Disable night schedule
                  value: "night_schedule_disabled"              
        night_time:
          name: Night set time
          description: >

          default: "00:10:00"
          selector:
            time:     
        night_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    wakeup_settings:
      name: "wakeup"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_wakeup_schedule:
          name: Enable wakeup schedule
          description: >
            This setting enables the wakeup schedule.
          default: wakeup_schedule_disabled
          selector:
            select:
              options:
                - label: Enable wakeup schedule
                  value: "wakeup_schedule_enabled"
                - label: Disable wakeup schedule
                  value: "wakeup_schedule_disabled"                     
        wakeup_time:
          name: wakeup set time
          description: >

          default: "6:30:00"
          selector:
            time:       
        wakeup_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script
          
    morning_settings:
      name: "morning"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_morning_schedule:
          name: Enable morning schedule
          description: >
            This setting enables the morning schedule.
          default: morning_schedule_disabled
          selector:
            select:
              options:
                - label: Enable morning schedule
                  value: "morning_schedule_enabled"
                - label: Disable morning schedule
                  value: "morning_schedule_disabled"                     
        morning_time:
          name: morning set time
          description: >

          default: "22:00:00"
          selector:
            time:       
        morning_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    lunch_settings:
      name: "lunch"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_lunch_schedule:
          name: Enable lunch schedule
          description: >
            This setting enables the lunch schedule.
          default: lunch_schedule_disabled
          selector:
            select:
              options:
                - label: Enable lunch schedule
                  value: "lunch_schedule_enabled"
                - label: Disable lunch schedule
                  value: "lunch_schedule_disabled"                     
        lunch_time:
          name: lunch set time
          description: >

          default: "12:30:00"
          selector:
            time:       
        lunch_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    afternoon_settings:
      name: "afternoon"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_afternoon_schedule:
          name: Enable afternoon schedule
          description: >
            This setting enables the afternoon schedule.
          default: afternoon_schedule_disabled
          selector:
            select:
              options:
                - label: Enable afternoon schedule
                  value: "afternoon_schedule_enabled"
                - label: Disable afternoon schedule
                  value: "afternoon_schedule_disabled"                     
        afternoon_time:
          name: afternoon set time
          description: >

          default: "22:00:00"
          selector:
            time:       
        afternoon_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    dusk_settings:
      name: "dusk"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_dusk_schedule:
          name: Enable dusk schedule
          description: >
            This setting enables the dusk schedule.
          default: dusk_schedule_disabled
          selector:
            select:
              options:
                - label: Enable dusk schedule
                  value: "dusk_schedule_enabled"
                - label: Disable dusk schedule
                  value: "dusk_schedule_disabled"                     
        dusk_offset:
          name: dusk offset time
          description: >

          default: "-00:45:00"
          selector:
            time:       
        dusk_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    bedroom_settings:
      name: "bedroom"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_bedroom_schedule:
          name: Enable bedroom schedule
          description: >
            This setting enables the bedroom schedule.
          default: bedroom_schedule_disabled
          selector:
            select:
              options:
                - label: Enable bedroom schedule
                  value: "bedroom_schedule_enabled"
                - label: Disable bedroom schedule
                  value: "bedroom_schedule_disabled"                     
        bedroom_time:
          name: bedroom set time
          description: >

          default: "22:00:00"
          selector:
            time:       
        bedroom_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script
             
    Bathroom_settings:
      name: "Bathroom"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      
    food_settings:
      name: "Food"
      icon: mdi:food
      collapsed: true

    vacuum_settings:
      name: "Vacuum"
      icon: mdi:lightbulb-on-outline
      collapsed: true
             
    lighting_settings:
      name: "Lighting"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    other_settings:
      name: "Other"
      icon: mdi:lightbulb-on-outline
      collapsed: true


shabbat_trigger: !input shabbat_trigger
dinner_time: !input dinner_time
evening_time: !input evening_time
night_time: !input night_time
wakeup_time: !input wakeup_time
morning_time: !input morning_time
lunch_time: !input lunch_time
afternoon_time: !input afternoon_time
dusk_offset: !input dusk_offset
wakeup_time: !input wakeup_time
bedtime_time: !input bedtime_time




triggers:
  - trigger: state
    entity_id:
      - !input shabbat_trigger
    from: "off"
    to: "on"
    id: shabbat_start
  - at: !input dinner_time
    id: shabbat_dinner
    trigger: time
  - at: !input evening_time
    id: shabbat_evening
    trigger: time
  - at: !input night_time
    id: shabbat_night
    trigger: time
  - at: !input wakeup_time
    id: shabbat_wakeup
    trigger: time
  - at: !input morning_time
    id: shabbat_morning
    trigger: time
  - at: !input lunch_time
    id: shabbat_lunch
    trigger: time
  - at: !input afternoon_time
    id: shabbat_afternoon
    trigger: time
  - event: sunset
    offset: !input dusk_offset
    id: shabbat_dusk
    trigger: sun
  - at: !input bedtime_time
    id: shabbat_kid_bedtime
    trigger: time
    enabled: false
  - trigger: state
    entity_id:
      - !input shabbat_trigger
    from: "on"
    to: "off"
    id: shabbat_end
