blueprint:
  name: Shabbat Mode
  description: >
    # 🕎 Shabbat Mode

    **Version: .1**


    Shabbat Mode master automation

    Requires the Jewish Calendar integration

    <details>
    <summary>How it works:</summary>


      - **Trigger:**
        - Going to be lots of description here
    </details>


    Welcome to reach out for questions.


    Required = *
  domain: automation
  input:
    trigger:
      name: "Config *"
      icon: mdi:cog-outline
      collapsed: true
      input:
        motion_trigger:
          name: Trigger Sensor
          description: >
            The sensor which triggers this automation, generally from Jewish Calendar


          default: input_boolean.shabbat_active
          selector:
            entity:
              filter:
                domain:
                  - binary_sensor
              multiple: false
              
    start_settings:
      name: "Start *"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        start_scenes:
          name: Start Scenes, Scripts, Automations
          description: >
            

          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    end_settings:
      name: "End *"
      icon: mdi:lightbulb-on-outline
      collapsed: true

                            
    evening_settings:
      name: "Evening"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_evening_schedule:
          name: Enable evening schedule
          description: >
            This setting enables the evening schedule.
          default: evening_schedule_disabled
          selector:
            select:
              options:
                - label: Enable evening schedule
                  value: "evening_schedule_enabled"
                - label: Disable evening schedule
                  value: "evening_schedule_disabled"      
                  
        night_time:
          name: Evening set time
          description: >

          default: "22:00:00"
          selector:
            time:
        evening_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    night_settings:
      name: "Night"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        enable_night_schedule:
          name: Enable night schedule
          description: >
            This setting enables the night schedule.
          default: night_schedule_disabled
          selector:
            select:
              options:
                - label: Enable night schedule
                  value: "night_schedule_enabled"
                - label: Disable night schedule
                  value: "night_schedule_disabled"      
                  
        night_time:
          name: Night set time
          description: >

          default: "00:10:00"
          selector:
            time:
        night_scenes:
          name: Night Scenes, Scripts, Automations
          description: >
            
          default: []
          selector:
            target:
              entity:
                domain:
                  - automation
                  - scene
                  - script

    bedtime_settings:
      name: "Bedtime"
      icon: mdi:lightbulb-on-outline
      collapsed: true
              
    morning_settings:
      name: "Morning"
      icon: mdi:lightbulb-on-outline
      collapsed: true
              
    afternoon_settings:
      name: "Afternoon"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    bedroom_settings:
      name: "Bedroom"
      icon: mdi:lightbulb-on-outline
      collapsed: true
             
    Bathroom_settings:
      name: "Bathroom"
      icon: mdi:lightbulb-on-outline
      collapsed: true
      
    food_settings:
      name: "Food"
      icon: mdi:food
      collapsed: true

    vacuum_settings:
      name: "Vacuum"
      icon: mdi:lightbulb-on-outline
      collapsed: true
             
    lighting_settings:
      name: "Lighting"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    other_settings:
      name: "Other"
      icon: mdi:lightbulb-on-outline
      collapsed: true



      
