blueprint:
  name: Shabbat Mode
  description: >
    # 🕎 Shabbat Mode

    **Version: .1**


    Shabbat Mode master automation

    Requires the Jewish Calendar integration

    <details>
    <summary>How it works:</summary>


      - **Trigger:**
        - Going to be lots of description here
    </details>


    Welcome to reach out for questions.


    Required = *
  domain: automation
  input:
    trigger:
      name: "Config *"
      icon: mdi:cog-outline
      collapsed: true
      input:
        motion_trigger:
          name: Trigger Sensor
          description: >
            The sensor which triggers this automation, generally from Jewish Calendar


          default: input_boolean.shabbat_active
          selector:
            entity:
              filter:
                domain:
                  - binary_sensor
              multiple: false
              
    start_settings:
      name: "Start *"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    end_settings:
      name: "End *"
      icon: mdi:lightbulb-on-outline
      collapsed: true
              
    evening_settings:
      name: "Evening"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    night_settings:
      name: "Night"
      icon: mdi:lightbulb-on-outline
      collapsed: true
              
    morning_settings:
      name: "Morning"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    lunch_settings:
      name: "Lunch"
      icon: mdi:lightbulb-on-outline
      collapsed: true
              
    afternoon_settings:
      name: "Afternoon"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    bedroom_settings:
      name: "Bedroom"
      icon: mdi:lightbulb-on-outline
      collapsed: true
             
    Bathroom_settings:
      name: "Bathroom"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    vacuum_settings:
      name: "Vacuum"
      icon: mdi:lightbulb-on-outline
      collapsed: true
             
    lighting_settings:
      name: "Lighting"
      icon: mdi:lightbulb-on-outline
      collapsed: true

    other_settings:
      name: "Other"
      icon: mdi:lightbulb-on-outline
      collapsed: true



      
